import "./globals.css";
import Navebar from "@/Navbar/Nav";
import ContextProvider from "./Contex/Contex";
import Footer from "@/Footer/Footer";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={" h-full antialiased"}
    >
      <body className="min-h-full flex flex-col">
        <ContextProvider>
          <Navebar />
          {children}
          <Footer/>
          <ToastContainer />
        </ContextProvider>
      </body>
    </html>
  );
}
